version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tnp-network

  placement-portal:
    image: placement-portal:latest
    platform: linux/amd64
    build:
      context: .
    container_name: placement-portal
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tnp-network

volumes:
  mysql-data:

networks:
  tnp-network:
    driver: bridge
