package com.iiitdmj.placement_portal.constants;

public enum Position {
    HR_MANAGER,
    CAMPUS_RECRUITER,
    TALENT_ACQUISITION_SPECIALIST,
    HIRING_MANAGER,
    SOFTWARE_ENGINEER,
    SENIOR_SOFTWARE_ENGINEER,
    ENGINEERING_MANAGER,
    DIRECTOR_OF_ENGINEERING,
    DIRECTOR_OF_TALENT_ACQUISITION,
    VICE_PRESIDENT_OF_HIRING
}
